---
title: "Poisson Modeling"
author: "You Been PArk"
date: "2024-11-22"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load necessary libraries
library(data.table)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(AER)

# Load the dataset
data <- fread("Individual-level basic variable.csv")

# Filter out the 16-year-old girl
data <- subset(data, !(Age == 16 & Sex == "F"))

# Remove rows with NA values in variables used in the model
data <- data %>%
  filter(
    !is.na(Partners_count) &
    !is.na(Age) &
    !is.na(Sex) &
    !is.na(CaregiverImmigrate) &
    !is.na(CaregiverResidencyDuration)
  )


# Convert categorical variables to factors
data[, Sex := as.factor(Sex)]
data[, CaregiverImmigrate := as.factor(CaregiverImmigrate)]
data[, UserLanguage := as.factor(UserLanguage)]
```

```{r}
# Fit the Poisson regression model
poisson_model <- glm(
  Partners_count ~ Age + Sex + CaregiverImmigrate + CaregiverResidencyDuration + UserLanguage +
    Sex:CaregiverImmigrate,
  family = poisson(link = "log"),
  data = data
)

# Summarize the model
summary(poisson_model)
dispersiontest(poisson_model)

# Ensure columns are numeric
data$Partners_count <- as.numeric(data$Partners_count)
data$Age <- as.numeric(data$Age)
data$CaregiverResidencyDuration <- as.numeric(data$CaregiverResidencyDuration)

# Subset numeric variables
num_vars <- data %>%
  dplyr::select(Partners_count, Age, CaregiverResidencyDuration)

# Compute the correlation matrix
cor_matrix <- cor(num_vars, use = "complete.obs")

# Visualize the heatmap
library(ggcorrplot)
ggcorrplot(cor_matrix, lab = TRUE, hc.order = TRUE, colors = c("blue", "white", "red"))
```

```{r}
poisson_model <- glm(
  Partners_count ~ Age + Sex,
  family = poisson(link = "log"),
  data = data
)

# Summarize the model
summary(poisson_model)

```

```{r}
poisson_model <- glm(
  Partners_count ~ Age + Sex + CaregiverResidencyDuration,
  family = poisson(link = "log"),
  data = data
)

# Summarize the model
summary(poisson_model)


```

```{r}
poisson_model <- glm(
  Partners_count ~ Age + Sex + CaregiverResidencyDuration + UserLanguage,
  family = poisson(link = "log"),
  data = data
)

# Summarize the model
summary(poisson_model)

```

```{r}
poisson_model <- glm(
  Partners_count ~ Age + Sex + CaregiverImmigrate + CaregiverResidencyDuration +
    Sex:CaregiverImmigrate,
  family = poisson(link = "log"),
  data = data
)

# Summarize the model
summary(poisson_model)

dispersiontest(poisson_model)
```

```{r}
library(MASS)
nb_model <- glm.nb(Partners_count ~ Age + Sex + CaregiverImmigrate + CaregiverResidencyDuration +
    Sex:CaregiverImmigrate, data = data)
summary(nb_model)

```